### PR TITLE
Added ability to send messages to contacts

### PR DESCRIPTION
**Pull request by ian-lastname**
The message input and send works now, though we'll probably have to drastically change the code when the database is set. Of course, since the database isn't done yet (as far as I'm aware), all the new messages sent won't persist when you refresh the page. When a new message is sent, the message log will automatically scroll down to the new message. Also, submitting a new message automatically clears the form so that users don't have to delete everything they already sent.

Also, I renamed the parameter for MessageLog function in MessageLog.jsx from stuff to parameters.

### CODE REVIEW

**Review by sanehirakenji — APPROVED** [review]
Just gotta merge the main branch into this and fix the eslint error, but otherwise it looks good.

**Comment by sanehirakenji** [comment]
Actually since theres no overlap between main files, just gotta change the eslint error I believe.

**Comment by ian-lastname** [comment]
Wait, what's the eslint error?

**Comment by sanehirakenji** [comment]
You added a space to the end of local variables I think

**Pull request merged**
